version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    volumes:
      - ./docker/init.d:/docker-entrypoint-initdb.d
      - ./docker/conf.d:/etc/mysql/conf.d
    ports:
      - 3314:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=mysql"
      - "PMA_USER=test"
      - "PMA_PASSWORD=test"
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions